### ISSUE TITLE
Geen stylesheet verwijzing in de eerste lessen

### ISSUE THREAD

**Issue by hakkas** [eelcodijkstra/html-tutorial#13]
In de uitwerkpagina (index.html) van lesbrief 1, 2 en 3 zie ik een verwijzing naar een stijlblad, terwijl dat helemaal niet nodig is. Kan deze weg? Het brengt de leerlingen in verwarring, omdat ze niet weten wat het betekent.

**Comment by eelcodijkstra** [comment]
OK. (hetzelfde geldt dan ook voor het css-bestand zelf, lijkt mij; en voor de viewport meta-data.)
