### ISSUE TITLE
Linkjes?

### ISSUE THREAD

**Issue by hakkas** [eelcodijkstra/html-tutorial#15]
In lesbrief 3 had ik verwacht dat linkjes uitgelegd zouden worden. Kon ik niet vinden. Is het er wel?

**Comment by eelcodijkstra** [comment]
Bedoel je in het boek of in het tutorial? 
In tutorial 2 komen deze aan de orde (verwijzingen/links en URLs)

In het boek is dit onderdeel onderbedeeld" (zacht gezegd). Zal ik naar kijken.

**Comment by hakkas** [comment]
Ik laat de leerlingen alleen de tutorials doorwerken. Is het niet handig om daarin geen onderscheid te maken?

**Comment by eelcodijkstra** [comment]
Waar wilde je onderscheid tussen maken?

**Comment by hakkas** [comment]
Je hebt dus een boek en een tutorial. Volgens mij vinden de leerlingen het handiger (vooral in het begin) om een stuk tekst te hebben waarin alle uitleg staat en de opdrachten (dus beiden gecombineerd)..... Wat vind jij?

**Comment by eelcodijkstra** [comment]
De leerlingen kunnen het tutorial doorwerken - dat is redelijk compleet. Maar voor sommige onderwerpen heb je veel meer uitleg nodig, die past niet goed in het formaat van een tutorial. Dat kan in de vorm van leesstof, en/of in de vorm van een video of presentatie.

Wat mis je in het tutorial bij links/verwijzingen?

**Comment by hakkas** [comment]
Nou .. het zou wel handig zijn als ze leren hoe ze een linkje naar een andere (eigen) pagina kunnen maken. Dus het hele proces:
1) Maak een nieuwe tweede pagina
2) Maak op je eerste pagina een linkje naar je tweede pagina
3) Maak op je tweede pagina een linkje naar je eerste pagina
4) Maak een linkje naar je favoriete website ..

**Comment by eelcodijkstra** [comment]
Prima: het maken van een tweede pagina is met deze versie van Thimble mogelijk. Het tutorial was in eerste instantie voor de vorige versie gemaakt... Zal ik toevoegen.

Een link naar een andere website zit er al in. Ik denk dat ik dat als eerste opdracht gebruik (dus, in jouw lijst: 4, 1, 2, 3).

**Comment by hakkas** [comment]
Ontzettend fijn! Dank je!

**Comment by eelcodijkstra** [comment]
Toegevoegd in GitHub; Thimble heeft nog problemen met publiceren...
