### ISSUE TITLE
Lesbrief 4 non-serif

### ISSUE THREAD

**Issue by hakkas** [eelcodijkstra/html-tutorial#16]
In lesbrief 4 wordt ook non-serif gesproken. Moet dat niet sans-serif zijn?

**Comment by eelcodijkstra** [comment]
dank je! Inderdaad - wat dom, ik heb het zo snel mogelijk gecorrigeerd. Dankzij GitHub blijven dergelijke dommiteiten voor het nageslacht bewaard...
