### ISSUE TITLE
inline css

### ISSUE THREAD

**Issue by hakkas** [eelcodijkstra/html-tutorial#5]
In les 6 (en misschien ook een aantal andere lessen) zie ik dat er gebruik is gemaakt van inline css. Ik heb sterk de voorkeur om de leerlingen in beginsel te leren om uitsluitend met een extern css-bestand te werken.

**Comment by eelcodijkstra** [comment]
Hallo Hakan,

ik begrijp je punt; dat is nu met de nieuwe versie van Thimble gemakkelijker te realiseren ;-)

Ik gebruik inline css om twee redenen (ook als je wel gemakkelijk een css-bestand kunt gebruiken):
- een didactische: de koppeling tussen de stijl en het element is dan zeer direct, je hebt geen aparte constructie nodig voor de koppeling; dit maakt het eenvoudiger in te zien wat het resultaat is van een experiment in het zetten van de waarden;
- nog een didactische: in het geval van interactie met JavaScript koppel je de style-attributen direct aan het element: je verandert dan niet de css, maar zet het style-attribuut direct in het DOM-element.
In de uiteindelijke versie zie je in de html-tekst natuurlijk geen style-attributen meer…

Hoe deze didactische aspecten uitwerken tegenover het principe dat je in de praktijk geen style-attributen in html wilt zien, durf ik niet te zeggen.
We kunnen eenvoudig een versie maken die met de aparte css-bestanden werkt.

Groeten,
Eelco

**Comment by eelcodijkstra** [comment]
Hallo Hakan,

ik heb dit aangepast: op één plek na heb ik alle css in het aparte css-bestand gezet. Die ene plek is nog als didactische voorbeeld bedoeld.
Ik zal de teksten in de tutorials nalopen en aanpassen.

Overigens is vb6 vooral bedoeld als experimenteer-omgeving voor het box-concept en positionering.

Groeten,
Eelco

**Comment by eelcodijkstra** [comment]
Done
